esphome:
  name: genmon-rs232-bridge

substitutions:
  display_name: GenMon RS232 Bridge
  
esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  # Disable serial logging
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "GMSB"
    password: "complex1!"

captive_portal:
  
# Individual sensors
sensor:
  - platform: wifi_signal
    name: "$display_name WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "$display_name IP Address"
  - platform: version
    name: "$display_name ESPHome Version"

web_server:
  port: 80
  include_internal: true
  
switch:
  - platform: restart
    name: "GenMon Bridge Restart"

external_components:
  - source: github://skipfire/esphome-stream-server
    refresh: 0s

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: 2
  rx_pin: 15
  debug:
    direction: BOTH
    after:
      timeout: 100ms
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');   

stream_server:
   uart_id: uart_bus
   port: 6638
